[package]
name = "random_math_question_generator"
version = "4.0.0"
description = "Random math question generator made with HTML, CSS, and JS."
authors = ["richie-rich90454"]
license = "Apache-2.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "^2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "^2", features = ["tray-icon", "image-png"] }
tauri-utils = { version = "^2", features = [] }
tauri-plugin-shell = "^2"
tauri-plugin-updater = { version = "2.10.0" }
tauri-plugin-process = "2.3.1"
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.13", default-features = false, features = ["rustls", "json"] }
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "macros", "migrate"] }

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]
name = "random_math_question_generator"

[[bin]]
name = "randmatqugea"
path = "src/main.rs"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"
