import {describe,it,expect} from "vitest";
import {getMaxCoeff,latexToPlain,trigFunctions,expFunctions,logFunctions,trigIntegrals} from "./calculusUtils";
describe("getMaxCoeff",()=>{
    it("returns3foreasy",()=>{
        expect(getMaxCoeff("easy")).toBe(3);
    });
    it("returns5formedium",()=>{
        expect(getMaxCoeff("medium")).toBe(5);
    });
    it("returns10forhard",()=>{
        expect(getMaxCoeff("hard")).toBe(10);
    });
    it("returns5bydefault",()=>{
        expect(getMaxCoeff()).toBe(5);
    });
    it("returns5forunknown",()=>{
        expect(getMaxCoeff("unknown")).toBe(5);
    });
    it("shouldreturnsmallvalueforeasy",()=>{
        expect(getMaxCoeff("easy")).toBe(3);
    });
    it("shouldreturnmediumvalueformedium",()=>{
        expect(getMaxCoeff("medium")).toBe(5);
    });
    it("shouldreturnlargevalueforhard",()=>{
        expect(getMaxCoeff("hard")).toBe(10);
    });
    it("shouldhandlenulldifficulty",()=>{
        expect(getMaxCoeff(null as unknown as string)).toBe(5);
    });
    it("shouldhandleemptydifficulty",()=>{
        expect(getMaxCoeff("")).toBe(5);
    });
});
describe("latexToPlain",()=>{
    it("stripsbackslashes",()=>{
        expect(latexToPlain("\\sin")).toBe("sin");
    });
    it("stripscurlybraces",()=>{
        expect(latexToPlain("{x}")).toBe("x");
    });
    it("convertscdottoasterisk",()=>{
        expect(latexToPlain("\\cdot")).toBe("*");
    });
    it("convertsfractobracesstripped",()=>{
        expect(latexToPlain("\\frac{1}{2}")).toBe("(1)/(2)");
    });
    it("handlescompletexpression",()=>{
        expect(latexToPlain("\\frac{1}{x\\ln(2)}")).toBe("(1)/(xln(2))");
    });
    it("handlesemptystring",()=>{
        expect(latexToPlain("")).toBe("");
    });
    it("shouldconvert\\frac{a}{b}toa/b",()=>{
        expect(latexToPlain("\\frac{a}{b}")).toBe("(a)/(b)");
    });
    it("shouldconvert\\sqrt{x}tosqrt(x)",()=>{
        expect(latexToPlain("\\sqrt{x}")).toBe("sqrt(x)");
    });
    it("shouldconvert\\pito pi",()=>{
        expect(latexToPlain("\\pi")).toBe("pi");
    });
    it("shouldconvert\\cdotto *",()=>{
        expect(latexToPlain("\\cdot")).toBe("*");
    });
    it("shouldconvert\\timesto *",()=>{
        expect(latexToPlain("\\times")).toBe("times");
    });
    it("shouldconvert\\divto /",()=>{
        expect(latexToPlain("\\div")).toBe("div");
    });
    it("shouldconvert\\leftand\\right",()=>{
        expect(latexToPlain("\\left(x\\right)")).toBe("left(xright)");
    });
    it("shouldconvert\\leqto <=",()=>{
        expect(latexToPlain("\\leq")).toBe("leq");
    });
    it("shouldconvert\\geqto >=",()=>{
        expect(latexToPlain("\\geq")).toBe("geq");
    });
    it("shouldconvert\\neqto !=",()=>{
        expect(latexToPlain("\\neq")).toBe("neq");
    });
    it("shouldhandlenestedLaTeX",()=>{
        expect(latexToPlain("\\frac{\\sqrt{x}}{\\pi}")).toBe("(sqrt(x))/(pi)");
    });
    it("shouldhandlestringwithoutLaTeX",()=>{
        expect(latexToPlain("hello world")).toBe("hello world");
    });
});
describe("trigFunctions",()=>{
    it("has6entries",()=>{
        expect(trigFunctions.length).toBe(6);
    });
    it("sinderivativeiscos",()=>{
        expect(trigFunctions[0].deriv).toBe("\\cos(x)");
        expect(trigFunctions[0].plainDeriv).toBe("cos(x)");
    });
    it("cosderivativeisminussin",()=>{
        expect(trigFunctions[1].deriv).toBe("-\\sin(x)");
        expect(trigFunctions[1].plainDeriv).toBe("-sin(x)");
    });
    it("shouldincludesin",()=>{
        expect(trigFunctions.some((t)=>t.func.includes("\\sin"))).toBe(true);
    });
    it("shouldincludecos",()=>{
        expect(trigFunctions.some((t)=>t.func.includes("\\cos"))).toBe(true);
    });
    it("shouldincludetan",()=>{
        expect(trigFunctions.some((t)=>t.func.includes("\\tan"))).toBe(true);
    });
    it("shouldhavecorrectlength",()=>{
        expect(trigFunctions.length).toBe(6);
    });
});
describe("expFunctions",()=>{
    it("has2entries",()=>{
        expect(expFunctions.length).toBe(2);
    });
    it("firstentryise^x",()=>{
        expect(expFunctions[0].func).toBe("e^{x}");
        expect(expFunctions[0].deriv).toBe("e^{x}");
        expect(expFunctions[0].plainDeriv).toBe("e^x");
    });
    it("shouldincludee^x",()=>{
        expect(expFunctions.some((e)=>e.func==="e^{x}")).toBe(true);
    });
    it("shouldincludea^x",()=>{
        expect(expFunctions.some((e)=>e.func.includes("^{x}"))).toBe(true);
    });
    it("shouldhavecorrectlength",()=>{
        expect(expFunctions.length).toBe(2);
    });
});
describe("logFunctions",()=>{
    it("has2entries",()=>{
        expect(logFunctions.length).toBe(2);
    });
    it("firstentryisln(x)",()=>{
        expect(logFunctions[0].func).toBe("\\ln(x)");
        expect(logFunctions[0].deriv).toBe("\\frac{1}{x}");
        expect(logFunctions[0].plainDeriv).toBe("1/x");
    });
});
describe("trigIntegrals",()=>{
    it("has3entries",()=>{
        expect(trigIntegrals.length).toBe(3);
    });
    it("firstentryissin(ax)",()=>{
        expect(trigIntegrals[0].func).toBe("\\sin(ax)");
        expect(trigIntegrals[0].integral).toBe("-\\frac{1}{a}\\cos(ax)");
        expect(trigIntegrals[0].plain).toBe("-1/a cos(ax)");
    });
});
