import {describe,it,expect} from "vitest";
import {factorial,nPr,nCr,gcd,lcm,getMaxN,getDataRange,mean,median,mode,range,stdDev,getOrdinal} from "./discreteUtils";
describe("factorial",()=>{
    it("returns1for0",()=>{
        expect(factorial(0)).toBe(1);
    });
    it("returns1for1",()=>{
        expect(factorial(1)).toBe(1);
    });
    it("returns2for2",()=>{
        expect(factorial(2)).toBe(2);
    });
    it("returns6for3",()=>{
        expect(factorial(3)).toBe(6);
    });
    it("returns120for5",()=>{
        expect(factorial(5)).toBe(120);
    });
    it("handleslargenumbers",()=>{
        expect(factorial(10)).toBe(3628800);
    });
});
describe("permutations",()=>{
    it("returnsnfornP1",()=>{
        expect(nPr(7,1)).toBe(7);
    });
    it("returnsn!fornPn",()=>{
        expect(nPr(4,4)).toBe(24);
    });
    it("returns0whenrgreatern",()=>{
        expect(nPr(3,5)).toBe(0);
    });
    it("handlesn0andr0",()=>{
        expect(nPr(0,0)).toBe(1);
    });
    it("handlesnegativeinputs",()=>{
        expect(nPr(-2,1)).toBe(0);
    });
});
describe("combinations",()=>{
    it("returns1fornC0",()=>{
        expect(nCr(5,0)).toBe(1);
    });
    it("returnsnfornC1",()=>{
        expect(nCr(5,1)).toBe(5);
    });
    it("returnsn!/(r!(n-r)!)fornCr",()=>{
        expect(nCr(6,3)).toBe(20);
    });
    it("returns0whenrgreatern",()=>{
        expect(nCr(3,5)).toBe(0);
    });
    it("handlesn0andr0",()=>{
        expect(nCr(0,0)).toBe(1);
    });
    it("handlesnegativeinputs",()=>{
        expect(nCr(-2,1)).toBe(0);
    });
});
describe("gcd",()=>{
    it("returnsfirstwhensecondis0",()=>{
        expect(gcd(7,0)).toBe(7);
    });
    it("returnssecondwhenfirstis0",()=>{
        expect(gcd(0,5)).toBe(5);
    });
    it("handlesnegativenumbers",()=>{
        expect(gcd(-12,18)).toBe(6);
    });
    it("returns1forcoprime",()=>{
        expect(gcd(7,11)).toBe(1);
    });
    it("handlesequalnumbers",()=>{
        expect(gcd(9,9)).toBe(9);
    });
});
describe("lcm",()=>{
    it("returnsfirstwhensecondis0",()=>{
        expect(lcm(7,0)).toBe(0);
    });
    it("returns0whenfirstis0",()=>{
        expect(lcm(0,5)).toBe(0);
    });
    it("handlesnegativenumbers",()=>{
        expect(lcm(-4,6)).toBe(12);
    });
    it("calculateslcmcorrectly",()=>{
        expect(lcm(4,6)).toBe(12);
    });
    it("handlesequalnumbers",()=>{
        expect(lcm(8,8)).toBe(8);
    });
    it("handlescoprimenumbers",()=>{
        expect(lcm(5,7)).toBe(35);
    });
});
describe("getMaxN",()=>{
    it("returns6foreasy",()=>{
        expect(getMaxN("easy")).toBe(6);
    });
    it("returns8formedium",()=>{
        expect(getMaxN("medium")).toBe(8);
    });
    it("returns12forhard",()=>{
        expect(getMaxN("hard")).toBe(12);
    });
    it("returns8bydefault",()=>{
        expect(getMaxN()).toBe(8);
    });
});
describe("getDataRange",()=>{
    it("returnseasysetup",()=>{
        expect(getDataRange("easy")).toEqual({min:1,max:20,count:5});
    });
    it("returnsmediumsetup",()=>{
        expect(getDataRange()).toEqual({min:0,max:50,count:10});
    });
    it("returnshardsetup",()=>{
        expect(getDataRange("hard")).toEqual({min:-50,max:100,count:15});
    });
});
describe("mean",()=>{
    it("returns3for1to5",()=>{
        expect(mean([1,2,3,4,5])).toBe(3);
    });
    it("returns1fortwo1s",()=>{
        expect(mean([1,1])).toBe(1);
    });
});
describe("median",()=>{
    it("returns2forodd",()=>{
        expect(median([1,2,3])).toBe(2);
    });
    it("returns2.5foreven",()=>{
        expect(median([1,2,3,4])).toBe(2.5);
    });
});
describe("mode",()=>{
    it("returns1forsinglemode",()=>{
        expect(mode([1,1,2])).toEqual([1]);
    });
    it("returnsbothforbimodal",()=>{
        expect(mode([1,2])).toEqual([1,2]);
    });
});
describe("range",()=>{
    it("returns4for1to5",()=>{
        expect(range([1,5])).toBe(4);
    });
});
describe("stdDev",()=>{
    it("returns0forconstant",()=>{
        expect(stdDev([1,1,1])).toBe(0);
    });
    it("returns1for1and3",()=>{
        expect(stdDev([1,3])).toBe(1);
    });
});
describe("getOrdinal",()=>{
    it("returnsstfor1",()=>{
        expect(getOrdinal(1)).toBe("st");
    });
    it("returnsndfor2",()=>{
        expect(getOrdinal(2)).toBe("nd");
    });
    it("returnsrdfor3",()=>{
        expect(getOrdinal(3)).toBe("rd");
    });
    it("returnsthnfor11",()=>{
        expect(getOrdinal(11)).toBe("th");
    });
    it("returnsstfor21",()=>{
        expect(getOrdinal(21)).toBe("st");
    });
});
